### ISSUE TITLE
Adding many components breaks the InfoPane column

### ISSUE THREAD

**Issue by SneakySensei** [amanjagdev/react-builder#13]
When users add several components to their add, the spacing between the elements inside InfoPane starts to increase.
I've attached an example in the below screenshot.

![react-builder screenshot](https://user-images.githubusercontent.com/51155558/94872094-517a9f80-0469-11eb-81a3-cd157ea86436.png)

This is undesirable and can be fixed with some minor tweaks to the CSS.

**Comment by SneakySensei** [comment]
I can work on this issue. Please assign it to me.

**Comment by amanjagdev** [comment]
@SneakySensei  This is great but can you combine PRs regarding issue #15 and this one and do a single PR
