### ISSUE TITLE
Need a delete button to remove added components

### ISSUE THREAD

**Issue by SneakySensei** [amanjagdev/react-builder#15]
Currently, there's no way for the user to delete an added component.

If the user accidentally adds a component and then wants to remove it, the only way is to reload the app and start again. This is bad in bigger projects because the user will lose all their planning. A delete button beside every component is necessary.

The delete button can be a single SVG icon appended at the end of every component card.

**Comment by SneakySensei** [comment]
I want to work on this issue. I'll create a new handler called **handleDelete** that will be executed from the onClick of a "trash" svg that would be present after the "page" checkbox.

**Comment by amanjagdev** [comment]
@SneakySensei  Yeah sure you may work on that
