### ISSUE TITLE
Implement Dark mode in the web app

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/react-builder#17]
Implement dark mode through a toggle switch in a dark mode which switched between light and dark mode
Dark mode settings must persist even after refreshing the page

**Comment by itsnitinr** [comment]
I would like to work on this.

**Comment by TheNinza** [comment]
I would love to work on this, too... Can you assign me this please

**Comment by ananya0504** [comment]
Hi, I have recently started to work on UI. Can I suggest a design for the same?

**Comment by itsnitinr** [comment]
@amanjagdev You would like me to make any styling improvements?
![darkmode](https://user-images.githubusercontent.com/34748469/94987314-2dab7c80-0583-11eb-82be-aa91f28bf007.png)

**Comment by amanjagdev** [comment]
@itsnitinr I would suggest you also change the input boxes and their background to a darker one.
@ananya0504  If you have also started working on it, You can always share the Screen Shot or make a PR for the same
Whosoever PR's UI design will be better will be accepted.

@TheNinza As you can see 2 people have already started working on it.
So I would suggest you can work on some other issue that will be opened in a while.

**Comment by itsnitinr** [comment]
@amanjagdev Kindly check this out and let me know if anything else needs to be changed. The theme persists on reload. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34748469/94988991-fb078100-058e-11eb-848a-4ecaf913372b.gif)

**Comment by lapstjup** [comment]
Hey @amanjagdev I have raised a pull request #18 for this issue.
Let me know if this works for you. 
One thing I couldn't figure out was toggling github button theme without page reload so I have not implemented it. The 'data-color-theme' was not picking up the changes without reloading the page.

**Comment by itsnitinr** [comment]
Hi @lapstjup. Even I've resolved the issue over an hour ago. I was unaware that you were also working on it as you didn't leave a comment saying so. I was waiting for @amanjagdev's approval before I make a PR. I've sent a GIF above of the same.

**Comment by lapstjup** [comment]
Hey @itsnitinr no worries. I suppose @amanjagdev will choose according to his metrics of selection. I guess you should also raise a pull request for the same 😄. In case I had to first ask to pick up the issue then it's my fault 😅 .

**Comment by amanjagdev** [comment]
@itsnitinr and @lapstjup  I haven't assigned the particular issue to anyone, so technically all of you can make corresponding PRs 
but @itsnitinr  is correct, Its always a good practice to mention and discuss things in the issue first before making a PR.

This time I will be considering all your pull requests for review and would suggest some changes.
The best PR would be accepted and merged into the main branch.

**Comment by amanjagdev** [comment]
This issue has been resolved by PR #18
