### ISSUE TITLE
Make It Mobile Responsive

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/react-builder#21]
In order to make the web app mobile responsive, the following tasks need to be implemented.
- Only the left panel should be visible on the mobile view.
- If people are on a mobile device, it should show a small card at the bottom which will say "open this website on the desktop to access it".
- The visitor's and users count along with the GitHub buttons should also be visible on the mobile view also.

**Comment by vj-abishek** [comment]
@amanjagdev Can I work in it? Then please assign me.

**Comment by amanjagdev** [comment]
@vj-abishek  Sure.. you can work on that 👍

**Comment by vj-abishek** [comment]
`"open this website on the desktop to access it".` @amanjagdev  This must be fixed

**Comment by lapstjup** [comment]
Hey @amanjagdev can I pick this up too ?

**Comment by vj-abishek** [comment]
![Annotation 2020-10-04 175755](https://user-images.githubusercontent.com/43115551/95015557-31b2c980-066b-11eb-9f36-238a68825209.jpg)

@amanjagdev here it the final result. Need to change anything?

**Comment by amanjagdev** [comment]
@vj-abishek I will review your PR In a while...
@lapstjup Those suggestions look great to me... You can also make a PR for the same.

Whosoever's implementation will be good will be accepted and merged :)

**Comment by amanjagdev** [comment]
@lapstjup There is one thing I would like to add, It's regarding your point 3.
Making the application vertically scrollable and placing InfoPane above SettingsPane would destroy the overall look of it on bigger screen sizes and ratio.
Maybe if you can use queries for the device they are using then after a certain point, the settings pane would be shifted downwards. That would be a better solution in my eyes.
Can you do that?
Rest all the points are great and you may start implementing it.

**Comment by vj-abishek** [comment]
@amanjagdev I'm working on the PR

**Comment by lapstjup** [comment]
@amanjagdev Hey yes I will do that as per width only. I like the current look and feel with left - right focus. I will identify a suitable breakpoint and do the vertical change.

Also I will start working on them probably after an hour or so ? I hope time isn't a problem here.

**Comment by vj-abishek** [comment]
@amanjagdev here is the preview URL https://react-builder-lna355qyo.vercel.app/

**Comment by lapstjup** [comment]
This took longer than expected but here is the pull request for this issue - #23.

**Comment by amanjagdev** [comment]
The issue has been resolved by #23
