### ISSUE TITLE
Add GitHub Repo Links to the site

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/react-builder#4]
A "Star us on GitHub" and "Fork us on Github" button need to be added in the web application without disturbing the styling and working of the application.
It would help newcomers to contribute to the project by directly staring and forking the repo.

**Comment by harshalkaigaonkar** [comment]
Hey @amanjagdev , i would like to do that .

**Comment by amanjagdev** [comment]
> Hey @amanjagdev , i would like to do that .

Great... I hope you understand what feature is needed to be added. Please do the following and make a pull request for the same. Feel free to ping me if you encounter any problem while understanding the project structure.

**Comment by priyanshupardhi** [comment]
hey @amanjagdev , I understand that you would like to add two buttons 
Can you tell me where to put those buttons

**Comment by harshalkaigaonkar** [comment]
> > Hey @amanjagdev , i would like to do that .
> 
> Great... I hope you understand what feature is needed to be added. Please do the following and make a pull request for the same. Feel free to ping me if you encounter any problem while understanding the project structure.
> Shall I assign you to this issue?

sure.

**Comment by priyanshupardhi** [comment]
@harshalkaigaonkar Are you working on the issue

**Comment by amanjagdev** [comment]
> hey @amanjagdev , I understand that you would like to add two buttons
> Can you tell me where to put those buttons

Please do so without disturbing the current styling of the application
You may change the placement to somewhere else if that seems more suitable and goes with the look of the app.
![add_here](https://user-images.githubusercontent.com/34389172/94771423-c780f700-03d4-11eb-8116-9b184447a919.png)

**Comment by harshalkaigaonkar** [comment]
> @harshalkaigaonkar Are you working on the issue

Yeah man!

**Comment by harshalkaigaonkar** [comment]
hey @amanjagdev , had a problem..
you want both star and fork button on the website ?
or 
only fork button ?
cause function of both the buttons are to get user land on the repo.

**Comment by Sayan-dev** [comment]
I am too working on this issue ok?

**Comment by amanjagdev** [comment]
@Sayan-dev Actually @harshalkaigaonkar  is already working on this one and he has already made a first draft pull request, I hope that you can work on other issues which will be open soon :)

**Comment by Sayan-dev** [comment]
Oh sorry.....i almost completed it

**Comment by amanjagdev** [comment]
> Oh sorry.....i almost completed it
> can i make a pr for it?

Ya sure, If you are almost completed then you may make a PR for it...
If you implemented a better approach then we can also go with it.

PS: Next time make sure you mention in the chat if you want to work on an issue.

**Comment by Sukriti-sood** [comment]
Hey @amanjagdev  ,I want to work on this issue.Is it available or done?

**Comment by amanjagdev** [comment]
@Sukriti-sood some people are already working on this issue.. I would suggest you work on some other issues and more issues will be open soon enough

**Comment by amanjagdev** [comment]
The issue has been resolved :)
