### ISSUE TITLE
Add number of visitors and users 

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/react-builder#5]
There should be a small badge that shows how many people have visited the site and how many people are using the service.
It's more like analytics for the site.
Placement of these badges must fit well with the current styling and must not interfere with the current functioning.

"No of visitors" will increase as soon as someone visits the site.
"No of Users" will increase once the user clicks on "Create App" button.

**Comment by sruthiragupathy** [comment]
Hi, can i try this one?

**Comment by aravind-korada** [comment]
Hey,
Can I take this up?

**Comment by amanjagdev** [comment]
Sure @sruthiragupathy  and @aravind-korada  but if you both could explain the approach that you would follow to add that service... because this is a live stable release and any wrong move could have breaking changes.

Just want to know the approach :)

**Comment by aravind-korada** [comment]
Can track number of visitors using componentDidMount and number of users whenever someone clicks creat app.

Can store the values in a DB or a file.
File would be a better option I think.
or 
You can suggest where to store that values.

**Comment by aryan-chawla** [comment]
can i use node to solve your issue?

**Comment by Sayan-dev** [comment]
we just need an api.....and can u provide the ui for the badges?..the api should be publicly accessible and will be hit when the page loads......we need to save the user's ipaddress in a database and donot recount them once added in the database . Then the number of visitors will be the total users in the database, i think we need another api, which wil be hit when create app is selected which will just inclease the count in the database

**Comment by amanjagdev** [comment]
@Sayan-dev  In your approach, we are making a totally new API  just for the sake of analytics,
We would just be storing some sort of object (Visitor's data) right so this seems a bit overkill for the task to me.

**Comment by amanjagdev** [comment]
@aravind-korada  This project is made using hooks and no class-based component is used and secondly where will you be storing that file and how will you access that in live version

**Comment by Sayan-dev** [comment]
> @Sayan-dev In your approach, we are making a totally new API just for the sake of analytics,
> We would just be storing some sort of object (Visitor's data) right so this seems a bit overkill for the task to me.
Look we need to store the data somewhere and using a db is the best solution right?

**Comment by amanjagdev** [comment]
> > @Sayan-dev In your approach, we are making a totally new API just for the sake of analytics,
> > We would just be storing some sort of object (Visitor's data) right so this seems a bit overkill for the task to me.
> > Look we need to store the data somewhere and using a db is the best solution right?

Surely your point is justified, Although I would suggest something lighter.

**Comment by amanjagdev** [comment]
If anyone of you can try and implement in a lighter way ... 
Pull Requests are always welcome.

Best and optimised approach will be merged.

**Comment by bobbasworld** [comment]
> If anyone of you can try and implement in a lighter way ...
> Pull Requests are always welcome.
> 
> Best and optimised approach will be merged.

I'm willing to give this a crack @amanjagdev . I plan to implement this using an API I found which allows for the necessary functionality to be implemented.

All that needs to be done is to create a function that fetches the API, and then render the result to the DOM.

**Comment by amanjagdev** [comment]
@bobbasworld Sounds great to me...
Try implementing it without any breaking changes and I would be really happy If you could pull this off :)
Make a PR After you are done and then I can review it.

**Comment by bobbasworld** [comment]
> @bobbasworld Sounds great to me...
> Try implementing it without any breaking changes and I would be really happy If you could pull this off :)
> Make a PR After you are done and then I can review it.

Sure, I'm on it :)

**Comment by Sayan-dev** [comment]
But to display the data we need some kind of data storage...be it database or a file...and to interact we need apis..I know the project  has no relation with backend but for this data display we need that setup

**Comment by bobbasworld** [comment]
> @bobbasworld Sounds great to me...
> Try implementing it without any breaking changes and I would be really happy If you could pull this off :)
> Make a PR After you are done and then I can review it.

@amanjagdev where do you want to display the counts? Please share a screenshot

**Comment by amanjagdev** [comment]
@bobbasworld 
Somewhere near these arrows ... Where ever it fits nicely with the feel of the application.
![image](https://user-images.githubusercontent.com/34389172/94805753-80155d80-040a-11eb-86af-5bcc2a9649ee.png)

**Comment by amanjagdev** [comment]
The issue has been resolved 👍
